#MDI_IP_FOLDER:=mt6357
ccflags-y += -I$(srctree)/drivers/misc/mediatek/rtc-lk8563/inc
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/rtc/$(MDI_IP_FOLDER)
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/rtc/include

obj-y   +=  rtc-lk8563.o 

#MTK_MDI_IP_SRC:= $(MDI_IP_FOLDER)/

#IP dependent part
#obj-y += \
  ../rtc/$(MTK_MDI_IP_SRC)

  
